.TH hikiwiki 1 "March 2015"
.SH NAME
hikiwiki \- a tiny wiki compiler

.SH SYNOPSIS
.B hikiwiki
[\fB\-i, \-\-init]

.B hikiwiki
[\fB\-r, \-\-remove] repo

.SH DESCRIPTION
.B hikiwiki
helps you build a simple wiki or blog with markdown and git.
.PP
This is probably not the wiki compiler you are looking for. I wrote it as a
learning exercise in Haskell, so it misses many, many features you will need
in RL. Take a look at ikiwiki, it is far more mature and useful.

.SH OPTIONS
.nf
\-i,\ \-\-init
      Prompts for a repo name and owner. Creates a new shared repo based on
      the contents of etc/setup/auto-blog. The new repo contains an initial
      commit of files and is ready to clone and work on.

\-r,\ \-\-remove repo
      Deletes the repo specified.
.fi

